import { Component } from '@angular/core';

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
  styleUrls: ['./board.component.scss']
})
export class BoardComponent {
 
data = [
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',
head:'Disapointed',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
head:'Disapointed',
name:'Anonymous',
team:'Team B'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',
head:'Very happy',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
head:'Very Happy',
name:'Anonymous',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty',
head:'Possitive',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',
head:'Could be better',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',
head:'That was Awsome',

team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Carry',
head:'That was Awsome',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',
head:'Disapointed',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',
head:'Disapointed',

team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',head:'Custom',

team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',
head:'Very Happy',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
head:'Disapointed',
name:'Patty Carry',
team:'Team A'},
{content:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti quo eaque, excepturi autem qui molestiae magni? Hic iste eum esse nihil itaque quae amet, quisquam omnis, molestiae cumque, ratione consectetur!',
name:'Patty Carry',
head:'Possitive',
team:'Team A'},
]
}
